#skrypt drukujący drzewo
print("     *")
print("    * *")
print("   *   *")
print("  *     *")
print(" *       *")
print("****   ****")
print("   *   *")
print("   *   *")
print("   *   *")
print("   *****")